name: Create and publish ASF MapReady Docker image

on:
  workflow_dispatch: {}
  push:
    paths:
      - build/asf_mapready.Dockerfile
    tags:
      - "v*.*.*"


jobs:

  build-and-push-image:
    runs-on: ubuntu-latest

    env:
      REGISTRY: ghcr.io/asfadmin
      AWS_DEFAULT_REGION: us-west-2
      IMAGE_NAME: mapready
      TAG_NAME: ${{ github.ref_name }}

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: build/asf_mapready.Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG_NAME }}